// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1B181x1YxyubeZcdj90KxFJOA5r3wOgk',
    appId: '1:155260643576:web:cca0a643f676828623330d',
    messagingSenderId: '155260643576',
    projectId: 'mumz-213db',
    authDomain: 'mumz-213db.firebaseapp.com',
    storageBucket: 'mumz-213db.firebasestorage.app',
    measurementId: 'G-RMD712P2KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhbWXmokXNBXohb-o-G3atS90vzL-hVoI',
    appId: '1:155260643576:android:d8bb19453696f8b723330d',
    messagingSenderId: '155260643576',
    projectId: 'mumz-213db',
    storageBucket: 'mumz-213db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8UaB75bwjzgbl9BrNIJV_wPmqr7NaGos',
    appId: '1:155260643576:ios:f3c9980122208a9823330d',
    messagingSenderId: '155260643576',
    projectId: 'mumz-213db',
    storageBucket: 'mumz-213db.firebasestorage.app',
    iosBundleId: 'com.example.mamyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8UaB75bwjzgbl9BrNIJV_wPmqr7NaGos',
    appId: '1:155260643576:ios:f3c9980122208a9823330d',
    messagingSenderId: '155260643576',
    projectId: 'mumz-213db',
    storageBucket: 'mumz-213db.firebasestorage.app',
    iosBundleId: 'com.example.mamyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1B181x1YxyubeZcdj90KxFJOA5r3wOgk',
    appId: '1:155260643576:web:26293fad003256dc23330d',
    messagingSenderId: '155260643576',
    projectId: 'mumz-213db',
    authDomain: 'mumz-213db.firebaseapp.com',
    storageBucket: 'mumz-213db.firebasestorage.app',
    measurementId: 'G-75PKCH2GDC',
  );
}
