name: mamyapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  shared_preferences: ^2.2.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  record: ^6.1.2
  permission_handler: ^11.0.0
  path_provider: ^2.0.15

  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  get_it: ^7.2.0

  http: ^1.6.0
  just_audio: ^0.9.36

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  sqflite: ^2.2.8+4
  path: ^1.8.3

  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.4

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/